let mascotas = [
    { nombre: "Luna", 
    especie: "Perro", 
    raza: "Golden", 
    edad: 3, 
    peso: 10, 
    estado: "Critico", 
    nombrePropietario: "Juan", 
    documento: 15854325, 
    telefono: 3105487874, 
    correo: "juanpa@gmail.com", 
    imagen: "./public/img/golden.webp" 
    },

    { nombre: "Simba", 
    especie: "Gato", 
    raza: "Siamés", 
    edad: 2, 
    peso: 5, 
    estado: "Estable", 
    nombrePropietario: "María", 
    documento: 98765432, 
    telefono: 3001234567, 
    correo: "maria@gmail.com", 
    imagen: "./public/img/siames.webp" 
    },

    { nombre: "Max", 
    especie: "Perro", 
    raza: "Labrador", 
    edad: 5, 
    peso: 15, 
    estado: "Critico", 
    nombrePropietario: "Pedro", 
    documento: 65432178, 
    telefono: 3159876543, 
    correo: "pedro@gmail.com", 
    imagen: "./public/img/labrador.webp" 
    },

    { nombre: "Nala", 
    especie: "Gato", 
    raza: "Persa", 
    edad: 4, peso: 6, 
    estado: "Critico", 
    nombrePropietario: "Ana", 
    documento: 12345678, 
    telefono: 3204567890, 
    correo: "ana@gmail.com", 
    imagen: "./public/img/persa.webp" 
    },

    { nombre: "Rocky", 
    especie: "Perro", 
    raza: "Bulldog", 
    edad: 7, 
    peso: 20, 
    estado: "Estable", 
    nombrePropietario: "Luis", 
    documento: 54321678, 
    telefono: 3186543210, 
    correo: "luis@gmail.com", 
    imagen: "./public/img/bulldog.webp" 
    },

    { nombre: "Milo", 
    especie: "Gato", 
    raza: "Angora", 
    edad: 1, 
    peso: 4, 
    estado: "Critico", 
    nombrePropietario: "Juan", 
    documento: 87654321, 
    telefono: 3009876543, 
    correo: "sofia@gmail.com", 
    imagen: "./public/img/angora.webp" 
    },

    { nombre: "Bella", 
    especie: "Perro", 
    raza: "Chihuahua", 
    edad: 6, 
    peso: 3, 
    estado: "Estable", 
    nombrePropietario: "Carlos", 
    documento: 43218765, 
    telefono: 3107654321, 
    correo: "carlos@gmail.com", 
    imagen: "./public/img/chihuahua.webp" 
    },

    { nombre: "Oreo", 
    especie: "Gato", 
    raza: "Maine Coon", 
    edad: 3, peso: 8, 
    estado: "Estable", 
    nombrePropietario: "Laura", 
    documento: 56781234, 
    telefono: 3217890123, 
    correo: "laura@gmail.com", 
    imagen: "./public/img/mainecoon.webp" 
    },

    { nombre: "Coco", 
    especie: "Perro", 
    raza: "Pug", 
    edad: 4, 
    peso: 7, 
    estado: "Critico", 
    nombrePropietario: "Juan", 
    documento: 32178456, 
    telefono: 3146789012, 
    correo: "elena@gmail.com", 
    imagen: "./public/img/pug.webp" 
    },

    { nombre: "Lucky", 
    especie: "Gato", 
    raza: "Bombay", 
    edad: 2, 
    peso: 5, 
    estado: "Estable", 
    nombrePropietario: "Ana", 
    documento: 78123456, 
    telefono: 3195678901, 
    correo: "pablo@gmail.com", 
    imagen: "./public/img/bombay.webp" 
    }
];